### ISSUE TITLE
Currently this widget doesn't work on online hybrid

### ISSUE THREAD

**Issue by simo101** [mendixlabs/offline-search#3]
Currently this widget doesn't work on online hybrid. I think this is because it is trying to perform the wrong type of search. It is using the offline constraints and not the online ones.

**Comment by simo101** [comment]
I currently get the following error:

`com.mendix.connectionbus.ConnectionBusRuntimeException: An exception has occurred for the following request(s): 
	InternalLimitedXPathTextGetRequest (depth = -1, amount = 10): //Appointments.Appointment[not(NextAppointment) and Progress='NotStarted'][object Object]`

**Comment by mistaguy** [comment]
You are right, this widget does not work with Hybrid Online. We also identified it and we have resolved it. we are updating the mendix store this week with the next version.

**Comment by Andries-Smit** [comment]
Widget is deprecated, in favor of the list view controls. Which will work on hybrid
